/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServerErrorRouteImport } from './routes/server-error'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as AdministratorRouteImport } from './routes/administrator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as AdministratorIndexRouteImport } from './routes/administrator/index'
import { Route as MarketplaceSignInRouteImport } from './routes/marketplace/sign-in'
import { Route as MarketplaceRequestPhotosRouteImport } from './routes/marketplace/request-photos'
import { Route as MarketplaceRequestRouteImport } from './routes/marketplace/request'
import { Route as MarketplaceProvidersRouteImport } from './routes/marketplace/providers'
import { Route as MarketplaceHowItWorksRouteImport } from './routes/marketplace/how-it-works'
import { Route as MarketplaceForProvidersRouteImport } from './routes/marketplace/for-providers'
import { Route as MarketplaceBillingRouteImport } from './routes/marketplace/billing'
import { Route as AdministratorLoginRouteImport } from './routes/administrator/login'
import { Route as MarketplaceRequestsIndexRouteImport } from './routes/marketplace/requests.index'
import { Route as AdministratorTasksIndexRouteImport } from './routes/administrator/tasks.index'
import { Route as AdministratorRequestsIndexRouteImport } from './routes/administrator/requests.index'
import { Route as AdministratorProvidersIndexRouteImport } from './routes/administrator/providers.index'
import { Route as AdministratorPaymentsIndexRouteImport } from './routes/administrator/payments.index'
import { Route as MarketplaceRequestsRequestIdRouteImport } from './routes/marketplace/requests.$requestId'
import { Route as MarketplaceProvidersProviderIdRouteImport } from './routes/marketplace/providers.$providerId'
import { Route as AdministratorTasksTaskIdRouteImport } from './routes/administrator/tasks.$taskId'
import { Route as AdministratorRequestsRequestIdRouteImport } from './routes/administrator/requests.$requestId'
import { Route as AdministratorProvidersProviderIdRouteImport } from './routes/administrator/providers.$providerId'
import { Route as AdministratorPaymentsPaymentIdRouteImport } from './routes/administrator/payments.$paymentId'

const ServerErrorRoute = ServerErrorRouteImport.update({
  id: '/server-error',
  path: '/server-error',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministratorRoute = AdministratorRouteImport.update({
  id: '/administrator',
  path: '/administrator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AdministratorIndexRoute = AdministratorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdministratorRoute,
} as any)
const MarketplaceSignInRoute = MarketplaceSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceRequestPhotosRoute =
  MarketplaceRequestPhotosRouteImport.update({
    id: '/request-photos',
    path: '/request-photos',
    getParentRoute: () => MarketplaceRoute,
  } as any)
const MarketplaceRequestRoute = MarketplaceRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceProvidersRoute = MarketplaceProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceHowItWorksRoute = MarketplaceHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceForProvidersRoute = MarketplaceForProvidersRouteImport.update({
  id: '/for-providers',
  path: '/for-providers',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceBillingRoute = MarketplaceBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AdministratorLoginRoute = AdministratorLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdministratorRoute,
} as any)
const MarketplaceRequestsIndexRoute =
  MarketplaceRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => MarketplaceRoute,
  } as any)
const AdministratorTasksIndexRoute = AdministratorTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdministratorRoute,
} as any)
const AdministratorRequestsIndexRoute =
  AdministratorRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorProvidersIndexRoute =
  AdministratorProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorPaymentsIndexRoute =
  AdministratorPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AdministratorRoute,
  } as any)
const MarketplaceRequestsRequestIdRoute =
  MarketplaceRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => MarketplaceRoute,
  } as any)
const MarketplaceProvidersProviderIdRoute =
  MarketplaceProvidersProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => MarketplaceProvidersRoute,
  } as any)
const AdministratorTasksTaskIdRoute =
  AdministratorTasksTaskIdRouteImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorRequestsRequestIdRoute =
  AdministratorRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorProvidersProviderIdRoute =
  AdministratorProvidersProviderIdRouteImport.update({
    id: '/providers/$providerId',
    path: '/providers/$providerId',
    getParentRoute: () => AdministratorRoute,
  } as any)
const AdministratorPaymentsPaymentIdRoute =
  AdministratorPaymentsPaymentIdRouteImport.update({
    id: '/payments/$paymentId',
    path: '/payments/$paymentId',
    getParentRoute: () => AdministratorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administrator': typeof AdministratorRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/server-error': typeof ServerErrorRoute
  '/administrator/login': typeof AdministratorLoginRoute
  '/marketplace/billing': typeof MarketplaceBillingRoute
  '/marketplace/for-providers': typeof MarketplaceForProvidersRoute
  '/marketplace/how-it-works': typeof MarketplaceHowItWorksRoute
  '/marketplace/providers': typeof MarketplaceProvidersRouteWithChildren
  '/marketplace/request': typeof MarketplaceRequestRoute
  '/marketplace/request-photos': typeof MarketplaceRequestPhotosRoute
  '/marketplace/sign-in': typeof MarketplaceSignInRoute
  '/administrator/': typeof AdministratorIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/administrator/payments/$paymentId': typeof AdministratorPaymentsPaymentIdRoute
  '/administrator/providers/$providerId': typeof AdministratorProvidersProviderIdRoute
  '/administrator/requests/$requestId': typeof AdministratorRequestsRequestIdRoute
  '/administrator/tasks/$taskId': typeof AdministratorTasksTaskIdRoute
  '/marketplace/providers/$providerId': typeof MarketplaceProvidersProviderIdRoute
  '/marketplace/requests/$requestId': typeof MarketplaceRequestsRequestIdRoute
  '/administrator/payments/': typeof AdministratorPaymentsIndexRoute
  '/administrator/providers/': typeof AdministratorProvidersIndexRoute
  '/administrator/requests/': typeof AdministratorRequestsIndexRoute
  '/administrator/tasks/': typeof AdministratorTasksIndexRoute
  '/marketplace/requests/': typeof MarketplaceRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/server-error': typeof ServerErrorRoute
  '/administrator/login': typeof AdministratorLoginRoute
  '/marketplace/billing': typeof MarketplaceBillingRoute
  '/marketplace/for-providers': typeof MarketplaceForProvidersRoute
  '/marketplace/how-it-works': typeof MarketplaceHowItWorksRoute
  '/marketplace/providers': typeof MarketplaceProvidersRouteWithChildren
  '/marketplace/request': typeof MarketplaceRequestRoute
  '/marketplace/request-photos': typeof MarketplaceRequestPhotosRoute
  '/marketplace/sign-in': typeof MarketplaceSignInRoute
  '/administrator': typeof AdministratorIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/administrator/payments/$paymentId': typeof AdministratorPaymentsPaymentIdRoute
  '/administrator/providers/$providerId': typeof AdministratorProvidersProviderIdRoute
  '/administrator/requests/$requestId': typeof AdministratorRequestsRequestIdRoute
  '/administrator/tasks/$taskId': typeof AdministratorTasksTaskIdRoute
  '/marketplace/providers/$providerId': typeof MarketplaceProvidersProviderIdRoute
  '/marketplace/requests/$requestId': typeof MarketplaceRequestsRequestIdRoute
  '/administrator/payments': typeof AdministratorPaymentsIndexRoute
  '/administrator/providers': typeof AdministratorProvidersIndexRoute
  '/administrator/requests': typeof AdministratorRequestsIndexRoute
  '/administrator/tasks': typeof AdministratorTasksIndexRoute
  '/marketplace/requests': typeof MarketplaceRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administrator': typeof AdministratorRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/server-error': typeof ServerErrorRoute
  '/administrator/login': typeof AdministratorLoginRoute
  '/marketplace/billing': typeof MarketplaceBillingRoute
  '/marketplace/for-providers': typeof MarketplaceForProvidersRoute
  '/marketplace/how-it-works': typeof MarketplaceHowItWorksRoute
  '/marketplace/providers': typeof MarketplaceProvidersRouteWithChildren
  '/marketplace/request': typeof MarketplaceRequestRoute
  '/marketplace/request-photos': typeof MarketplaceRequestPhotosRoute
  '/marketplace/sign-in': typeof MarketplaceSignInRoute
  '/administrator/': typeof AdministratorIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/administrator/payments/$paymentId': typeof AdministratorPaymentsPaymentIdRoute
  '/administrator/providers/$providerId': typeof AdministratorProvidersProviderIdRoute
  '/administrator/requests/$requestId': typeof AdministratorRequestsRequestIdRoute
  '/administrator/tasks/$taskId': typeof AdministratorTasksTaskIdRoute
  '/marketplace/providers/$providerId': typeof MarketplaceProvidersProviderIdRoute
  '/marketplace/requests/$requestId': typeof MarketplaceRequestsRequestIdRoute
  '/administrator/payments/': typeof AdministratorPaymentsIndexRoute
  '/administrator/providers/': typeof AdministratorProvidersIndexRoute
  '/administrator/requests/': typeof AdministratorRequestsIndexRoute
  '/administrator/tasks/': typeof AdministratorTasksIndexRoute
  '/marketplace/requests/': typeof MarketplaceRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrator'
    | '/marketplace'
    | '/server-error'
    | '/administrator/login'
    | '/marketplace/billing'
    | '/marketplace/for-providers'
    | '/marketplace/how-it-works'
    | '/marketplace/providers'
    | '/marketplace/request'
    | '/marketplace/request-photos'
    | '/marketplace/sign-in'
    | '/administrator/'
    | '/marketplace/'
    | '/administrator/payments/$paymentId'
    | '/administrator/providers/$providerId'
    | '/administrator/requests/$requestId'
    | '/administrator/tasks/$taskId'
    | '/marketplace/providers/$providerId'
    | '/marketplace/requests/$requestId'
    | '/administrator/payments/'
    | '/administrator/providers/'
    | '/administrator/requests/'
    | '/administrator/tasks/'
    | '/marketplace/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/server-error'
    | '/administrator/login'
    | '/marketplace/billing'
    | '/marketplace/for-providers'
    | '/marketplace/how-it-works'
    | '/marketplace/providers'
    | '/marketplace/request'
    | '/marketplace/request-photos'
    | '/marketplace/sign-in'
    | '/administrator'
    | '/marketplace'
    | '/administrator/payments/$paymentId'
    | '/administrator/providers/$providerId'
    | '/administrator/requests/$requestId'
    | '/administrator/tasks/$taskId'
    | '/marketplace/providers/$providerId'
    | '/marketplace/requests/$requestId'
    | '/administrator/payments'
    | '/administrator/providers'
    | '/administrator/requests'
    | '/administrator/tasks'
    | '/marketplace/requests'
  id:
    | '__root__'
    | '/'
    | '/administrator'
    | '/marketplace'
    | '/server-error'
    | '/administrator/login'
    | '/marketplace/billing'
    | '/marketplace/for-providers'
    | '/marketplace/how-it-works'
    | '/marketplace/providers'
    | '/marketplace/request'
    | '/marketplace/request-photos'
    | '/marketplace/sign-in'
    | '/administrator/'
    | '/marketplace/'
    | '/administrator/payments/$paymentId'
    | '/administrator/providers/$providerId'
    | '/administrator/requests/$requestId'
    | '/administrator/tasks/$taskId'
    | '/marketplace/providers/$providerId'
    | '/marketplace/requests/$requestId'
    | '/administrator/payments/'
    | '/administrator/providers/'
    | '/administrator/requests/'
    | '/administrator/tasks/'
    | '/marketplace/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministratorRoute: typeof AdministratorRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  ServerErrorRoute: typeof ServerErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/server-error': {
      id: '/server-error'
      path: '/server-error'
      fullPath: '/server-error'
      preLoaderRoute: typeof ServerErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrator': {
      id: '/administrator'
      path: '/administrator'
      fullPath: '/administrator'
      preLoaderRoute: typeof AdministratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/administrator/': {
      id: '/administrator/'
      path: '/'
      fullPath: '/administrator/'
      preLoaderRoute: typeof AdministratorIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/marketplace/sign-in': {
      id: '/marketplace/sign-in'
      path: '/sign-in'
      fullPath: '/marketplace/sign-in'
      preLoaderRoute: typeof MarketplaceSignInRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/request-photos': {
      id: '/marketplace/request-photos'
      path: '/request-photos'
      fullPath: '/marketplace/request-photos'
      preLoaderRoute: typeof MarketplaceRequestPhotosRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/request': {
      id: '/marketplace/request'
      path: '/request'
      fullPath: '/marketplace/request'
      preLoaderRoute: typeof MarketplaceRequestRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/providers': {
      id: '/marketplace/providers'
      path: '/providers'
      fullPath: '/marketplace/providers'
      preLoaderRoute: typeof MarketplaceProvidersRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/how-it-works': {
      id: '/marketplace/how-it-works'
      path: '/how-it-works'
      fullPath: '/marketplace/how-it-works'
      preLoaderRoute: typeof MarketplaceHowItWorksRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/for-providers': {
      id: '/marketplace/for-providers'
      path: '/for-providers'
      fullPath: '/marketplace/for-providers'
      preLoaderRoute: typeof MarketplaceForProvidersRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/billing': {
      id: '/marketplace/billing'
      path: '/billing'
      fullPath: '/marketplace/billing'
      preLoaderRoute: typeof MarketplaceBillingRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/administrator/login': {
      id: '/administrator/login'
      path: '/login'
      fullPath: '/administrator/login'
      preLoaderRoute: typeof AdministratorLoginRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/marketplace/requests/': {
      id: '/marketplace/requests/'
      path: '/requests'
      fullPath: '/marketplace/requests/'
      preLoaderRoute: typeof MarketplaceRequestsIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/administrator/tasks/': {
      id: '/administrator/tasks/'
      path: '/tasks'
      fullPath: '/administrator/tasks/'
      preLoaderRoute: typeof AdministratorTasksIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/requests/': {
      id: '/administrator/requests/'
      path: '/requests'
      fullPath: '/administrator/requests/'
      preLoaderRoute: typeof AdministratorRequestsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/providers/': {
      id: '/administrator/providers/'
      path: '/providers'
      fullPath: '/administrator/providers/'
      preLoaderRoute: typeof AdministratorProvidersIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/payments/': {
      id: '/administrator/payments/'
      path: '/payments'
      fullPath: '/administrator/payments/'
      preLoaderRoute: typeof AdministratorPaymentsIndexRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/marketplace/requests/$requestId': {
      id: '/marketplace/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/marketplace/requests/$requestId'
      preLoaderRoute: typeof MarketplaceRequestsRequestIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/providers/$providerId': {
      id: '/marketplace/providers/$providerId'
      path: '/$providerId'
      fullPath: '/marketplace/providers/$providerId'
      preLoaderRoute: typeof MarketplaceProvidersProviderIdRouteImport
      parentRoute: typeof MarketplaceProvidersRoute
    }
    '/administrator/tasks/$taskId': {
      id: '/administrator/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/administrator/tasks/$taskId'
      preLoaderRoute: typeof AdministratorTasksTaskIdRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/requests/$requestId': {
      id: '/administrator/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/administrator/requests/$requestId'
      preLoaderRoute: typeof AdministratorRequestsRequestIdRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/providers/$providerId': {
      id: '/administrator/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/administrator/providers/$providerId'
      preLoaderRoute: typeof AdministratorProvidersProviderIdRouteImport
      parentRoute: typeof AdministratorRoute
    }
    '/administrator/payments/$paymentId': {
      id: '/administrator/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/administrator/payments/$paymentId'
      preLoaderRoute: typeof AdministratorPaymentsPaymentIdRouteImport
      parentRoute: typeof AdministratorRoute
    }
  }
}

interface AdministratorRouteChildren {
  AdministratorLoginRoute: typeof AdministratorLoginRoute
  AdministratorIndexRoute: typeof AdministratorIndexRoute
  AdministratorPaymentsPaymentIdRoute: typeof AdministratorPaymentsPaymentIdRoute
  AdministratorProvidersProviderIdRoute: typeof AdministratorProvidersProviderIdRoute
  AdministratorRequestsRequestIdRoute: typeof AdministratorRequestsRequestIdRoute
  AdministratorTasksTaskIdRoute: typeof AdministratorTasksTaskIdRoute
  AdministratorPaymentsIndexRoute: typeof AdministratorPaymentsIndexRoute
  AdministratorProvidersIndexRoute: typeof AdministratorProvidersIndexRoute
  AdministratorRequestsIndexRoute: typeof AdministratorRequestsIndexRoute
  AdministratorTasksIndexRoute: typeof AdministratorTasksIndexRoute
}

const AdministratorRouteChildren: AdministratorRouteChildren = {
  AdministratorLoginRoute: AdministratorLoginRoute,
  AdministratorIndexRoute: AdministratorIndexRoute,
  AdministratorPaymentsPaymentIdRoute: AdministratorPaymentsPaymentIdRoute,
  AdministratorProvidersProviderIdRoute: AdministratorProvidersProviderIdRoute,
  AdministratorRequestsRequestIdRoute: AdministratorRequestsRequestIdRoute,
  AdministratorTasksTaskIdRoute: AdministratorTasksTaskIdRoute,
  AdministratorPaymentsIndexRoute: AdministratorPaymentsIndexRoute,
  AdministratorProvidersIndexRoute: AdministratorProvidersIndexRoute,
  AdministratorRequestsIndexRoute: AdministratorRequestsIndexRoute,
  AdministratorTasksIndexRoute: AdministratorTasksIndexRoute,
}

const AdministratorRouteWithChildren = AdministratorRoute._addFileChildren(
  AdministratorRouteChildren,
)

interface MarketplaceProvidersRouteChildren {
  MarketplaceProvidersProviderIdRoute: typeof MarketplaceProvidersProviderIdRoute
}

const MarketplaceProvidersRouteChildren: MarketplaceProvidersRouteChildren = {
  MarketplaceProvidersProviderIdRoute: MarketplaceProvidersProviderIdRoute,
}

const MarketplaceProvidersRouteWithChildren =
  MarketplaceProvidersRoute._addFileChildren(MarketplaceProvidersRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceBillingRoute: typeof MarketplaceBillingRoute
  MarketplaceForProvidersRoute: typeof MarketplaceForProvidersRoute
  MarketplaceHowItWorksRoute: typeof MarketplaceHowItWorksRoute
  MarketplaceProvidersRoute: typeof MarketplaceProvidersRouteWithChildren
  MarketplaceRequestRoute: typeof MarketplaceRequestRoute
  MarketplaceRequestPhotosRoute: typeof MarketplaceRequestPhotosRoute
  MarketplaceSignInRoute: typeof MarketplaceSignInRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceRequestsRequestIdRoute: typeof MarketplaceRequestsRequestIdRoute
  MarketplaceRequestsIndexRoute: typeof MarketplaceRequestsIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceBillingRoute: MarketplaceBillingRoute,
  MarketplaceForProvidersRoute: MarketplaceForProvidersRoute,
  MarketplaceHowItWorksRoute: MarketplaceHowItWorksRoute,
  MarketplaceProvidersRoute: MarketplaceProvidersRouteWithChildren,
  MarketplaceRequestRoute: MarketplaceRequestRoute,
  MarketplaceRequestPhotosRoute: MarketplaceRequestPhotosRoute,
  MarketplaceSignInRoute: MarketplaceSignInRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceRequestsRequestIdRoute: MarketplaceRequestsRequestIdRoute,
  MarketplaceRequestsIndexRoute: MarketplaceRequestsIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministratorRoute: AdministratorRouteWithChildren,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  ServerErrorRoute: ServerErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
