/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestRouteImport } from './routes/request'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestSuccessRouteImport } from './routes/request.success'
import { Route as ProvidersProviderIdRouteImport } from './routes/providers.$providerId'

const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestSuccessRoute = RequestSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => RequestRoute,
} as any)
const ProvidersProviderIdRoute = ProvidersProviderIdRouteImport.update({
  id: '/$providerId',
  path: '/$providerId',
  getParentRoute: () => ProvidersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/request': typeof RequestRouteWithChildren
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/request/success': typeof RequestSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/request': typeof RequestRouteWithChildren
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/request/success': typeof RequestSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/request': typeof RequestRouteWithChildren
  '/providers/$providerId': typeof ProvidersProviderIdRoute
  '/request/success': typeof RequestSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/providers'
    | '/request'
    | '/providers/$providerId'
    | '/request/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/providers'
    | '/request'
    | '/providers/$providerId'
    | '/request/success'
  id:
    | '__root__'
    | '/'
    | '/providers'
    | '/request'
    | '/providers/$providerId'
    | '/request/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  RequestRoute: typeof RequestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/success': {
      id: '/request/success'
      path: '/success'
      fullPath: '/request/success'
      preLoaderRoute: typeof RequestSuccessRouteImport
      parentRoute: typeof RequestRoute
    }
    '/providers/$providerId': {
      id: '/providers/$providerId'
      path: '/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof ProvidersProviderIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
  }
}

interface ProvidersRouteChildren {
  ProvidersProviderIdRoute: typeof ProvidersProviderIdRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersProviderIdRoute: ProvidersProviderIdRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

interface RequestRouteChildren {
  RequestSuccessRoute: typeof RequestSuccessRoute
}

const RequestRouteChildren: RequestRouteChildren = {
  RequestSuccessRoute: RequestSuccessRoute,
}

const RequestRouteWithChildren =
  RequestRoute._addFileChildren(RequestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  RequestRoute: RequestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
