/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServerErrorRouteImport } from './routes/server-error'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MarketplaceSignInRouteImport } from './routes/marketplace/sign-in'
import { Route as MarketplaceRequestPhotosRouteImport } from './routes/marketplace/request-photos'
import { Route as MarketplaceRequestRouteImport } from './routes/marketplace/request'
import { Route as MarketplaceProvidersRouteImport } from './routes/marketplace/providers'
import { Route as MarketplaceHowItWorksRouteImport } from './routes/marketplace/how-it-works'
import { Route as MarketplaceForProvidersRouteImport } from './routes/marketplace/for-providers'
import { Route as MarketplaceBillingRouteImport } from './routes/marketplace/billing'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as MarketplaceRequestsIndexRouteImport } from './routes/marketplace/requests.index'
import { Route as AdminTasksIndexRouteImport } from './routes/admin/tasks.index'
import { Route as AdminRequestsIndexRouteImport } from './routes/admin/requests.index'
import { Route as AdminProvidersIndexRouteImport } from './routes/admin/providers.index'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin/payments.index'
import { Route as MarketplaceRequestsRequestIdRouteImport } from './routes/marketplace/requests.$requestId'
import { Route as MarketplaceProvidersProviderIdRouteImport } from './routes/marketplace/providers.$providerId'
import { Route as AdminTasksTaskIdRouteImport } from './routes/admin/tasks.$taskId'
import { Route as AdminRequestsRequestIdRouteImport } from './routes/admin/requests.$requestId'
import { Route as AdminProvidersProviderIdRouteImport } from './routes/admin/providers.$providerId'
import { Route as AdminPaymentsPaymentIdRouteImport } from './routes/admin/payments.$paymentId'

const ServerErrorRoute = ServerErrorRouteImport.update({
  id: '/server-error',
  path: '/server-error',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MarketplaceSignInRoute = MarketplaceSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceRequestPhotosRoute =
  MarketplaceRequestPhotosRouteImport.update({
    id: '/request-photos',
    path: '/request-photos',
    getParentRoute: () => MarketplaceRoute,
  } as any)
const MarketplaceRequestRoute = MarketplaceRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceProvidersRoute = MarketplaceProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceHowItWorksRoute = MarketplaceHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceForProvidersRoute = MarketplaceForProvidersRouteImport.update({
  id: '/for-providers',
  path: '/for-providers',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceBillingRoute = MarketplaceBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => MarketplaceRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const MarketplaceRequestsIndexRoute =
  MarketplaceRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => MarketplaceRoute,
  } as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsIndexRoute = AdminRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersIndexRoute = AdminProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AdminRoute,
} as any)
const MarketplaceRequestsRequestIdRoute =
  MarketplaceRequestsRequestIdRouteImport.update({
    id: '/requests/$requestId',
    path: '/requests/$requestId',
    getParentRoute: () => MarketplaceRoute,
  } as any)
const MarketplaceProvidersProviderIdRoute =
  MarketplaceProvidersProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => MarketplaceProvidersRoute,
  } as any)
const AdminTasksTaskIdRoute = AdminTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRequestIdRoute = AdminRequestsRequestIdRouteImport.update({
  id: '/requests/$requestId',
  path: '/requests/$requestId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersProviderIdRoute =
  AdminProvidersProviderIdRouteImport.update({
    id: '/providers/$providerId',
    path: '/providers/$providerId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPaymentsPaymentIdRoute = AdminPaymentsPaymentIdRouteImport.update({
  id: '/payments/$paymentId',
  path: '/payments/$paymentId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/server-error': typeof ServerErrorRoute
  '/admin/login': typeof AdminLoginRoute
  '/marketplace/billing': typeof MarketplaceBillingRoute
  '/marketplace/for-providers': typeof MarketplaceForProvidersRoute
  '/marketplace/how-it-works': typeof MarketplaceHowItWorksRoute
  '/marketplace/providers': typeof MarketplaceProvidersRouteWithChildren
  '/marketplace/request': typeof MarketplaceRequestRoute
  '/marketplace/request-photos': typeof MarketplaceRequestPhotosRoute
  '/marketplace/sign-in': typeof MarketplaceSignInRoute
  '/admin/': typeof AdminIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/admin/providers/$providerId': typeof AdminProvidersProviderIdRoute
  '/admin/requests/$requestId': typeof AdminRequestsRequestIdRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRoute
  '/marketplace/providers/$providerId': typeof MarketplaceProvidersProviderIdRoute
  '/marketplace/requests/$requestId': typeof MarketplaceRequestsRequestIdRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/providers/': typeof AdminProvidersIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/marketplace/requests/': typeof MarketplaceRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/server-error': typeof ServerErrorRoute
  '/admin/login': typeof AdminLoginRoute
  '/marketplace/billing': typeof MarketplaceBillingRoute
  '/marketplace/for-providers': typeof MarketplaceForProvidersRoute
  '/marketplace/how-it-works': typeof MarketplaceHowItWorksRoute
  '/marketplace/providers': typeof MarketplaceProvidersRouteWithChildren
  '/marketplace/request': typeof MarketplaceRequestRoute
  '/marketplace/request-photos': typeof MarketplaceRequestPhotosRoute
  '/marketplace/sign-in': typeof MarketplaceSignInRoute
  '/admin': typeof AdminIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/admin/providers/$providerId': typeof AdminProvidersProviderIdRoute
  '/admin/requests/$requestId': typeof AdminRequestsRequestIdRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRoute
  '/marketplace/providers/$providerId': typeof MarketplaceProvidersProviderIdRoute
  '/marketplace/requests/$requestId': typeof MarketplaceRequestsRequestIdRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/admin/providers': typeof AdminProvidersIndexRoute
  '/admin/requests': typeof AdminRequestsIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/marketplace/requests': typeof MarketplaceRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/server-error': typeof ServerErrorRoute
  '/admin/login': typeof AdminLoginRoute
  '/marketplace/billing': typeof MarketplaceBillingRoute
  '/marketplace/for-providers': typeof MarketplaceForProvidersRoute
  '/marketplace/how-it-works': typeof MarketplaceHowItWorksRoute
  '/marketplace/providers': typeof MarketplaceProvidersRouteWithChildren
  '/marketplace/request': typeof MarketplaceRequestRoute
  '/marketplace/request-photos': typeof MarketplaceRequestPhotosRoute
  '/marketplace/sign-in': typeof MarketplaceSignInRoute
  '/admin/': typeof AdminIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/admin/payments/$paymentId': typeof AdminPaymentsPaymentIdRoute
  '/admin/providers/$providerId': typeof AdminProvidersProviderIdRoute
  '/admin/requests/$requestId': typeof AdminRequestsRequestIdRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRoute
  '/marketplace/providers/$providerId': typeof MarketplaceProvidersProviderIdRoute
  '/marketplace/requests/$requestId': typeof MarketplaceRequestsRequestIdRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/providers/': typeof AdminProvidersIndexRoute
  '/admin/requests/': typeof AdminRequestsIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/marketplace/requests/': typeof MarketplaceRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/marketplace'
    | '/server-error'
    | '/admin/login'
    | '/marketplace/billing'
    | '/marketplace/for-providers'
    | '/marketplace/how-it-works'
    | '/marketplace/providers'
    | '/marketplace/request'
    | '/marketplace/request-photos'
    | '/marketplace/sign-in'
    | '/admin/'
    | '/marketplace/'
    | '/admin/payments/$paymentId'
    | '/admin/providers/$providerId'
    | '/admin/requests/$requestId'
    | '/admin/tasks/$taskId'
    | '/marketplace/providers/$providerId'
    | '/marketplace/requests/$requestId'
    | '/admin/payments/'
    | '/admin/providers/'
    | '/admin/requests/'
    | '/admin/tasks/'
    | '/marketplace/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/server-error'
    | '/admin/login'
    | '/marketplace/billing'
    | '/marketplace/for-providers'
    | '/marketplace/how-it-works'
    | '/marketplace/providers'
    | '/marketplace/request'
    | '/marketplace/request-photos'
    | '/marketplace/sign-in'
    | '/admin'
    | '/marketplace'
    | '/admin/payments/$paymentId'
    | '/admin/providers/$providerId'
    | '/admin/requests/$requestId'
    | '/admin/tasks/$taskId'
    | '/marketplace/providers/$providerId'
    | '/marketplace/requests/$requestId'
    | '/admin/payments'
    | '/admin/providers'
    | '/admin/requests'
    | '/admin/tasks'
    | '/marketplace/requests'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/marketplace'
    | '/server-error'
    | '/admin/login'
    | '/marketplace/billing'
    | '/marketplace/for-providers'
    | '/marketplace/how-it-works'
    | '/marketplace/providers'
    | '/marketplace/request'
    | '/marketplace/request-photos'
    | '/marketplace/sign-in'
    | '/admin/'
    | '/marketplace/'
    | '/admin/payments/$paymentId'
    | '/admin/providers/$providerId'
    | '/admin/requests/$requestId'
    | '/admin/tasks/$taskId'
    | '/marketplace/providers/$providerId'
    | '/marketplace/requests/$requestId'
    | '/admin/payments/'
    | '/admin/providers/'
    | '/admin/requests/'
    | '/admin/tasks/'
    | '/marketplace/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  ServerErrorRoute: typeof ServerErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/server-error': {
      id: '/server-error'
      path: '/server-error'
      fullPath: '/server-error'
      preLoaderRoute: typeof ServerErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/marketplace/sign-in': {
      id: '/marketplace/sign-in'
      path: '/sign-in'
      fullPath: '/marketplace/sign-in'
      preLoaderRoute: typeof MarketplaceSignInRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/request-photos': {
      id: '/marketplace/request-photos'
      path: '/request-photos'
      fullPath: '/marketplace/request-photos'
      preLoaderRoute: typeof MarketplaceRequestPhotosRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/request': {
      id: '/marketplace/request'
      path: '/request'
      fullPath: '/marketplace/request'
      preLoaderRoute: typeof MarketplaceRequestRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/providers': {
      id: '/marketplace/providers'
      path: '/providers'
      fullPath: '/marketplace/providers'
      preLoaderRoute: typeof MarketplaceProvidersRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/how-it-works': {
      id: '/marketplace/how-it-works'
      path: '/how-it-works'
      fullPath: '/marketplace/how-it-works'
      preLoaderRoute: typeof MarketplaceHowItWorksRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/for-providers': {
      id: '/marketplace/for-providers'
      path: '/for-providers'
      fullPath: '/marketplace/for-providers'
      preLoaderRoute: typeof MarketplaceForProvidersRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/billing': {
      id: '/marketplace/billing'
      path: '/billing'
      fullPath: '/marketplace/billing'
      preLoaderRoute: typeof MarketplaceBillingRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/marketplace/requests/': {
      id: '/marketplace/requests/'
      path: '/requests'
      fullPath: '/marketplace/requests/'
      preLoaderRoute: typeof MarketplaceRequestsIndexRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/tasks'
      fullPath: '/admin/tasks/'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests/': {
      id: '/admin/requests/'
      path: '/requests'
      fullPath: '/admin/requests/'
      preLoaderRoute: typeof AdminRequestsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers/': {
      id: '/admin/providers/'
      path: '/providers'
      fullPath: '/admin/providers/'
      preLoaderRoute: typeof AdminProvidersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/payments'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/marketplace/requests/$requestId': {
      id: '/marketplace/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/marketplace/requests/$requestId'
      preLoaderRoute: typeof MarketplaceRequestsRequestIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/providers/$providerId': {
      id: '/marketplace/providers/$providerId'
      path: '/$providerId'
      fullPath: '/marketplace/providers/$providerId'
      preLoaderRoute: typeof MarketplaceProvidersProviderIdRouteImport
      parentRoute: typeof MarketplaceProvidersRoute
    }
    '/admin/tasks/$taskId': {
      id: '/admin/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/admin/tasks/$taskId'
      preLoaderRoute: typeof AdminTasksTaskIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests/$requestId': {
      id: '/admin/requests/$requestId'
      path: '/requests/$requestId'
      fullPath: '/admin/requests/$requestId'
      preLoaderRoute: typeof AdminRequestsRequestIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers/$providerId': {
      id: '/admin/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/admin/providers/$providerId'
      preLoaderRoute: typeof AdminProvidersProviderIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments/$paymentId': {
      id: '/admin/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/admin/payments/$paymentId'
      preLoaderRoute: typeof AdminPaymentsPaymentIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPaymentsPaymentIdRoute: typeof AdminPaymentsPaymentIdRoute
  AdminProvidersProviderIdRoute: typeof AdminProvidersProviderIdRoute
  AdminRequestsRequestIdRoute: typeof AdminRequestsRequestIdRoute
  AdminTasksTaskIdRoute: typeof AdminTasksTaskIdRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
  AdminProvidersIndexRoute: typeof AdminProvidersIndexRoute
  AdminRequestsIndexRoute: typeof AdminRequestsIndexRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPaymentsPaymentIdRoute: AdminPaymentsPaymentIdRoute,
  AdminProvidersProviderIdRoute: AdminProvidersProviderIdRoute,
  AdminRequestsRequestIdRoute: AdminRequestsRequestIdRoute,
  AdminTasksTaskIdRoute: AdminTasksTaskIdRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
  AdminProvidersIndexRoute: AdminProvidersIndexRoute,
  AdminRequestsIndexRoute: AdminRequestsIndexRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MarketplaceProvidersRouteChildren {
  MarketplaceProvidersProviderIdRoute: typeof MarketplaceProvidersProviderIdRoute
}

const MarketplaceProvidersRouteChildren: MarketplaceProvidersRouteChildren = {
  MarketplaceProvidersProviderIdRoute: MarketplaceProvidersProviderIdRoute,
}

const MarketplaceProvidersRouteWithChildren =
  MarketplaceProvidersRoute._addFileChildren(MarketplaceProvidersRouteChildren)

interface MarketplaceRouteChildren {
  MarketplaceBillingRoute: typeof MarketplaceBillingRoute
  MarketplaceForProvidersRoute: typeof MarketplaceForProvidersRoute
  MarketplaceHowItWorksRoute: typeof MarketplaceHowItWorksRoute
  MarketplaceProvidersRoute: typeof MarketplaceProvidersRouteWithChildren
  MarketplaceRequestRoute: typeof MarketplaceRequestRoute
  MarketplaceRequestPhotosRoute: typeof MarketplaceRequestPhotosRoute
  MarketplaceSignInRoute: typeof MarketplaceSignInRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MarketplaceRequestsRequestIdRoute: typeof MarketplaceRequestsRequestIdRoute
  MarketplaceRequestsIndexRoute: typeof MarketplaceRequestsIndexRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceBillingRoute: MarketplaceBillingRoute,
  MarketplaceForProvidersRoute: MarketplaceForProvidersRoute,
  MarketplaceHowItWorksRoute: MarketplaceHowItWorksRoute,
  MarketplaceProvidersRoute: MarketplaceProvidersRouteWithChildren,
  MarketplaceRequestRoute: MarketplaceRequestRoute,
  MarketplaceRequestPhotosRoute: MarketplaceRequestPhotosRoute,
  MarketplaceSignInRoute: MarketplaceSignInRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MarketplaceRequestsRequestIdRoute: MarketplaceRequestsRequestIdRoute,
  MarketplaceRequestsIndexRoute: MarketplaceRequestsIndexRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  ServerErrorRoute: ServerErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
